[package]
name = "basic-things"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "caesar-cipher"
path = "src/caesar-cipher.rs"

[[bin]]
name = "trait-object"
path = "src/trait-object.rs"

[dependencies]
